### ISSUE TITLE
GeistMono rendering weird ligature when using `!==`

### ISSUE THREAD

**Issue by queirozlc** [vercel/geist-font#103]
**Font Name (Geist Sans/Geist Mono):**
- [ ] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
Something weird has been happening when i trying to use the `!==` with Geist Mono and ligatures, looks like it's rendering with some glitch or something like that and this is happening in both VSCode and my terminal emulators.

**Steps to Reproduce:**
1.  open VSCode or some terminal emulator such as alacritty, kitty etc
2. type `!==`

**Expected Behavior:**
Should render something like that:

<img width="302" alt="image" src="https://github.com/vercel/geist-font/assets/91512054/4e15af71-e18d-4cc3-a9ab-446ac21180d8">

**Screenshots:**
At the moment is rendering something like that:

<img width="336" alt="image" src="https://github.com/vercel/geist-font/assets/91512054/a664005c-c553-4c7a-b832-edbc06547d76">

**Environment (please complete the following information):**
 - OS: MacOS Sonoma 14.4.1
 - Software: VsCode, Terminal Emulators (Tested on kitty, Wezterm and Alacritty)
 - Version of the Font: 1.3.0

**Additional Context**
I've noticed that this glitch only happens with some specific weights such as 500, 600, 700

<img width="1264" alt="image" src="https://github.com/vercel/geist-font/assets/91512054/378971a1-e126-4be9-acd2-29bfdce7890d">

**Comment by guidoferreyra** [comment]
It’s fixed on version 1.4.0
