### ISSUE TITLE
Font Weight with Geist Sans on web

### ISSUE THREAD

**Issue by pirimihave** [vercel/geist-font#105]
Help plzzzzz with Geist Sans pairing. Multiple font weights get mixed up when used on the website / am using Wordpress
>>>> Regular 400 pair like Thin...

<img width="224" alt="Capture d’écran 2024-05-13 à 18 21 18" src="https://github.com/vercel/geist-font/assets/66082369/148988a2-f2e4-4c0d-8340-2b31623eb41e">
<img width="538" alt="Capture d’écran 2024-05-13 à 18 21 34" src="https://github.com/vercel/geist-font/assets/66082369/867686ea-6a59-4cc0-a9ef-3084c99a4b37">

**Comment by guidoferreyra** [comment]
See https://github.com/vercel/geist-font/issues/12#issuecomment-2022819202
