### ISSUE TITLE
Rename variable fonts

### ISSUE THREAD

**Issue by fnky** [vercel/geist-font#11]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [x] Geist Mono

**Description of the Issue:**

Rename variable fonts so that they can be installed alongside TTF.

This is useful when you want to use it in applications that does not support variable fonts, while being able to use them in applications that do.

On macOS it will show up as duplicate due to naming conflicts.

**Comment by anasrar** [comment]
Same thing happen on linux `fc-list | grep "Geist Mono"`:
![image](https://github.com/vercel/geist-font/assets/38805204/458550ac-ac40-4051-94b4-a5e3d8ea79c3)

Inter use `Inter V` for variable version.

**Comment by JohnPhamous** [comment]
Fixed in #46 and available in the `1.0.1` release on [GitHub](https://github.com/vercel/geist-font/releases/tag/1.0.1) and on [npm](https://www.npmjs.com/package/geist).
