### ISSUE TITLE
Text Stroke Rendering Issue

### ISSUE THREAD

**Issue by kyrylolvov** [vercel/geist-font#112]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [ ] Geist Mono

**Description of the Issue:**
The Geist Sans font is incorrectly rendered when applying `-webkit-text-stroke-color` property.

**Steps to Reproduce:**
Apply these styles:
```
-webkit-text-fill-color: white;
-webkit-text-stroke-width: 2px;
-webkit-text-stroke-color: black;
```

**Screenshots:**
<img width="403" alt="Screenshot 2024-06-05 at 10 17 43 AM" src="https://github.com/vercel/geist-font/assets/70720713/a0447ba0-8671-4fc1-b8e0-29d61a09f8de">

**Environment (please complete the following information):**
 - OS: MacOS
 - Software: Arc Browser
 - Version of the Font: 1.3

**Comment by kyrylolvov** [comment]
@guidoferreyra Hello! Is this on the roadmap of fixes? As I saw a similar issue, but it was closed by the author.

**Comment by guidoferreyra** [comment]
On variable fonts is needed to keep the overlaps for better and smoother inteporlation. Unfortunately this get is the way of using outlines and strokes. Is supossed that browsers and apps will change the way of how they apply outlines to text but is not possible to know when this will happen.

There is a CSS workaround using text shadow
```
.outline-text {
    color: white;
    text-shadow: 1px 1px 0 #000, -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;
}
```

**Comment by kyrylolvov** [comment]
> Hi @kyrylolvov! On variable fonts it’s needed to keep the overlaps for better and smoother inteporlation. Unfortunately this get is the way of using outlines and strokes. It’s supossed that browsers and apps will change the way of how they apply outlines to text but is not possible to know when this will happen.
> 
> There is a CSS workaround using text shadow
> 
> ```
> .outline-text {
>     color: white;
>     text-shadow: 1px 1px 0 #000, -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;
> }
> ```

Thank you for your answer and assistance, it works! :)

**Comment by sm3sher** [comment]
Thanks for the workaround! Just a small note: the `text-shadow` could be simplified by removing the last redundant shadow, as the first four already cover all directions:

```css
.outline-text {
    color: white;
    text-shadow: 
        1px 1px 0 #000,  /* Bottom-right */
       -1px -1px 0 #000, /* Top-left */
        1px -1px 0 #000, /* Top-right */
       -1px 1px 0 #000;  /* Bottom-left */
}
```
