### ISSUE TITLE
Invalid link to the license in the readme.md

### ISSUE THREAD

**Issue by Razushi** [vercel/geist-font#113]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
The link to the license in the readme.md contains a typo and sends you to ~geist-font/blob/main/LICENSE.TXT

**Steps to Reproduce:**
1. Click on the link in the header `License` in the readme file.

**Expected Behavior:**
The link should correctly send user to ~geist-font/blob/main/LICENSE.txt

**Screenshots:**
![image](https://github.com/vercel/geist-font/assets/111180787/2f3c7860-0207-465e-9f6d-91adeb87be2d)

**Environment (please complete the following information):**
 - OS: Any
 - Software: Browser
 - Version of the Font: N/A

**Additional Context:**

**Comment by JohnPhamous** [comment]
Fixed!
