### ISSUE TITLE
Variable font weight scales are incorrect.

### ISSUE THREAD

**Issue by vijaywargiya** [vercel/geist-font#12]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
Variable font weight scales are incorrect. Font loads up as bold when font-weight is normal.

**Steps to Reproduce:**
1. Use @font-face to set up any of the variable font files. GeistVF.ttf / GeistVF.woff2 / GeistMonoVF.woff2 / GeistMonoVF.ttf
```
@font-face {
    font-family: "Geist";
    src: url("../fonts/GeistVF.ttf");
}
```
2. Setup font with tailwind 
```
    theme: {
      extend: {
          fontFamily: {
              geist: ["Geist"],
```
3. Use for an element.
`className={"font-geist"}`

**Expected Behavior:**
Font should respect font-weight and rendered accordingly.

**Screenshots:**
<img width="314" alt="Screenshot 2023-10-28 at 2 34 30 AM" src="https://github.com/vercel/geist-font/assets/35684108/d0d41a2b-18b4-42af-9720-04c7f157aa15">

**Environment:**
 - OS:  MacOS
 - Software: React + Tailwind
 - Version of the Font: 1.0

**Comment by kasem-sm** [comment]
+1

**Comment by atsixian** [comment]
Looks like the weight names are also incorrect. `Regular` is thinner than `UltraLight` and `Light`.


<img width="600" alt="geist regular" src="https://github.com/vercel/geist-font/assets/43892874/7ddabb66-a89a-476e-9147-99fa86ccb5fd">
<img width="600" alt="geist light" src="https://github.com/vercel/geist-font/assets/43892874/aa263e3b-9f1c-4e53-92a6-ed04858a3191">

**Comment by Mrahmani71** [comment]
Same problem

![image](https://github.com/vercel/geist-font/assets/13013819/12fe4fc3-6b75-447a-b1e2-2aee396d6a62)

**Comment by mwskwong** [comment]
I wonder if this is related to when using this font in a Word document and exporting it to PDF, all the text will appear super thin despite only medium and bold being used for the entire document and Adobe Reader suggests both weights of the fonts are embedded.

**Comment by didier** [comment]
Geist is unusable in its current state.

**Comment by ivanjeremic** [comment]
I installed the font and try to use it inside vscode but adding setting in setting "Geist Mono" does nothing it falls back to default font, any idea why?

**Comment by kenmcd** [comment]
The design coordinates are being used as the instance weights in the variable fonts.
So the variable fonts are not going to work until that is fixed.

The static fonts should work.
Their weight settings are correct (with the exception of UltraBlack).

**Comment by cristiancoppari** [comment]
Same problem here. I installed the font in VSCode. If I use the font with 400 of weight, it looks very thin. If I set the font weight to 500 its a bit bold, but usable.

**Comment by JohnPhamous** [comment]
Fixed in #46 and available in the `1.0.1` release on [GitHub](https://github.com/vercel/geist-font/releases/tag/1.0.1) and on [npm](https://www.npmjs.com/package/geist).

**Comment by chungweileong94** [comment]
> Fixed in #46 and available in the `1.0.1` release on [GitHub](https://github.com/vercel/geist-font/releases/tag/1.0.1) and on [npm](https://www.npmjs.com/package/geist).

@JohnPhamous Unfortunately, the issue doesn't seem to be fixed.

**Comment by JohnPhamous** [comment]
> > Fixed in #46 and available in the `1.0.1` release on [GitHub](https://github.com/vercel/geist-font/releases/tag/1.0.1) and on [npm](https://www.npmjs.com/package/geist).
> 
> @JohnPhamous Unfortunately, the issue doesn't seem to be fixed.
> 
> ![image](https://user-images.githubusercontent.com/15154097/281246681-f67b32b6-8744-4cdd-aacb-38cb181f8ec3.png)

How can I repro your setup? The weight axis was remapped from 100-900.

**Comment by chungweileong94** [comment]
> > > Fixed in #46 and available in the `1.0.1` release on [GitHub](https://github.com/vercel/geist-font/releases/tag/1.0.1) and on [npm](https://www.npmjs.com/package/geist).
> 
> > 
> 
> > @JohnPhamous Unfortunately, the issue doesn't seem to be fixed.
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/15154097/281246681-f67b32b6-8744-4cdd-aacb-38cb181f8ec3.png)
> 
> 
> 
> How can I repro your setup? The weight axis was remapped from 100-900.

I basically just install the font via Homebrew, then inspect the variable font in fontbook on MacOS.

**Comment by kpollich** [comment]
I downloaded the 1.0.1 release of Geist Mono from the releases tab on GitHub, and installed via Font Book on macOS. The font is incredibly thin by default in VS Code:

![image](https://github.com/vercel/geist-font/assets/6766512/fc670bf8-fa7d-4ea3-b8d2-d16962b5ae0b)

I'm using the `Geist Mono Variable` font family included in the `.zip` archive for the 1.0.1 release. 

Here's the same chunk of code in JetBrain Mono:

![image](https://github.com/vercel/geist-font/assets/6766512/3bc4fa08-6c8e-4e2a-ba1d-9fd26dc11d7b)

Weirdly, the font seems to render at the expected weight in iTerm. e.g. here's the same code chunk side by side in Vim/iTerm and VS Code: 

![image](https://github.com/vercel/geist-font/assets/6766512/24ba999f-8e14-4bad-aad3-a120e3f6c371)

**Comment by kpollich** [comment]
I wound up just installing all of the `.otf` fonts individually and using `Geist Mono` instead of `Geist Mono Variable` and that renders at the expected weight 🤷

**Comment by psugihara** [comment]
I also had to go back to 1.0.0 and the old way of importing `import { GeistSans, GeistMono } from "geist/font";
` to make weights work correctly on my site. Does this add to the bundle size?

**Comment by chengluyu** [comment]
Hello everyone! I’ve found a solution to fix this issue (refer to #68). Since the team of Geist font hasn’t responded yet, I’ve created [a release in my own fork](https://github.com/chengluyu/geist-font/releases/tag/1.1.0-alpha.0). Feel free to give it a try!

**Comment by vinhphm** [comment]
The issue still persists in the variable fonts. I think this shouldn't be marked as Closed.

**Comment by JohnPhamous** [comment]
We are updating the variable font. We will create a new release soon.

**Comment by guidoferreyra** [comment]
This should be fixed on the latest release https://github.com/vercel/geist-font/releases/tag/1.3.0

A note for the people using the fonts on web, when defining the @font-face rule dont forget to define the font-weight as a range:

eg.

```
@font-face {
  font-family: "Geist";
  src: url("path/to/font/file/GeistVF.woff2") format("woff2-variations");
  font-weight: 100 900;
  font-style: normal;  
}
```
