### ISSUE TITLE
Is the font's npm package only intended for use in next js?

### ISSUE THREAD

**Issue by sarojregmi200** [vercel/geist-font#120]
First of all thank you for such a beautiful font Vercel and Basement Studio.
I love the font, am using it locally but due to some issues, I am getting some compatibility issues with it.
So, I tried to use the npm package of the font.
which resulted in an error.

So, Wanted to ask is the font's [npm package](https://www.npmjs.com/package/geist?activeTab=readme) only intended for use in  for next js?

> I don't know if this issue should be here regardless, I was unable to find any discussion setup so, opened the issue.

**Comment by sarojregmi200** [comment]
I am getting similar issue as #107.

**Comment by JohnPhamous** [comment]
The `geist` npm package only supports Next.js right now.

To use the font outside of Next.js, you can download the font files and use them in your project as you would with any custom font.
