### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by darnfish** [vercel/geist-font#13]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [ ] Geist Mono

**Description of the Issue:**
```
project_root/node_modules/geist/dist/font.js:1
import localFont from "@next/font/local";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Environment (please complete the following information):**
 - OS: macOS

**Additional Context:**
My `package.json` does not include `type: module`

**Comment by JohnPhamous** [comment]
@darnfish can you provide a Codesandbox/Replit/repo that repros the problem?

**Comment by washedlih** [comment]
have this issue as well

**Comment by ckrook** [comment]
Hello, me to!

**Comment by stijnelskens** [comment]
Bump, also having this issue

**Comment by ethndotsh** [comment]
me as well

**Comment by heyarviind** [comment]
getting same issue

**Comment by iamdevmarcos** [comment]
the same issue here

**Comment by aryanprince** [comment]
Apparently this error only shows up on `pages` router. Can someone vouch for this?

I built two new Nextjs 14 apps (`app` and `pages`), installed Geist font, and added `GeistSans.classNames` to `_app.tsx` and `layout.tsx` respectively.

App router version works fine, pages router one shows the same 'Cannot use import statement outside a module' error.

Link to repos I tested this with: [Pages Router (error)](https://github.com/aryanprince/nextjs-14-pages) & [App Router (all good)](https://github.com/aryanprince/nextjs-14-pages)

**Comment by jacobthesheep** [comment]
Also couldn't get Geist package to work in Astro

**Comment by dieharders** [comment]
Same issue.
Using "pages" router.

Next.js: v14.0.1
React: v18.2.0

**Comment by eriksik2** [comment]
Also getting this error on nextjs v13.5.4 with pages router.

**Comment by carloscdante** [comment]
Also getting this error.

**Comment by AnimeAllstar** [comment]
me too. Looks that they didn't bother testing it with the pages router.

**Comment by JonHMChan** [comment]
Also getting this error with pages

**Comment by hkgnp** [comment]
Having this issue with pages router as well.

**Comment by enricoros** [comment]
Same - pages router, NextJS 13.4.19 (not updating to13.5/14 because of larger bundle sizes)

**Comment by kiltedDev** [comment]
> Next 13: Error After Import Geist Font -> SyntaxError: Cannot use import statement outside a module #27

This fixed it for me as well.

    "next": "^13.5.4",
    "react": "18.2.0",
    
   using Bun as package manager for this one.

**Comment by VapidLinus** [comment]
@darnfish I don't think this issue should be closed.

It's great we found a workaround, but this is still an issue imo until they add this to the installation instructions on the website or the npm page.

**Comment by hkgnp** [comment]
> @darnfish I don't think this issue should be closed.
> 
> It's great we found a workaround, but this is still an issue imo until they add this to the installation instructions on the website or the npm page.

I think so too. It seems like the source of the issue has not been discovered yet.

**Comment by aryanprince** [comment]
I made a new issue (#59) with more information about this issue, check it out. Hopefully it gets resolved.

@VapidLinus @hkgnp

**Comment by troneras** [comment]
Try adding this line on the top of your fonts file

`/// <reference types="geist/font/sans" />`

Explanation: You may have in your tsconfig a rule to exclude node_modules, which means TypeScript will not check or include any files from the node_modules directory.

One solution could be to remove "node_modules" from the exclude array, but this might significantly slow down TypeScript, as it will start checking all files in node_modules.

A better solution is to add that triple slash directive on the top of the file. This directive will tell TypeScript to include that specific module in the compilation context. This way, TypeScript will include the geist/font module in the compilation context, even though node_modules is excluded in tsconfig.json.

If it doesn't work try restarting the ts server:
- Press Ctrl+Shift+P to open the command palette.
- Type "TypeScript: Restart TS server" and select it.
