### ISSUE TITLE
Kerning

### ISSUE THREAD

**Issue by vv-monsalve** [vercel/geist-font#135]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans

**Description of the Issue:**
After pulling the latest files at commit `7b2c26c` some kerning issues are spotted.

### Numerals
- Mainly the `7`
    
    <img width="742" alt="Screenshot 2024-10-08 at 17 18 20" src="https://github.com/user-attachments/assets/5e98dbeb-91f0-43e1-950e-30bf45c438e6">

    <img width="1725" alt="Screenshot 2024-10-08 at 17 34 51" src="https://github.com/user-attachments/assets/24180e24-7219-49df-8e12-ce88377647c9">

### Uppercase

- Mainly `LY` `LV` `AYA` `LT`
    <img width="789" alt="Screenshot 2024-10-08 at 17 22 30" src="https://github.com/user-attachments/assets/8bee5c94-31c8-4e4b-b170-037c2eadb71c">
    <img width="834" alt="Screenshot 2024-10-08 at 17 23 04" src="https://github.com/user-attachments/assets/5780a041-d9d5-468d-9e62-97d00d282cb6">
    <img width="946" alt="Screenshot 2024-10-08 at 17 23 13" src="https://github.com/user-attachments/assets/5c1f0d08-bf17-46d4-a8d5-818a4ef0bfbb">

### Lowercase
- Mainly `Yo` `Ye`
- The `tilde` in `ñ` is lighter than other marks

    <img width="1038" alt="Screenshot 2024-10-08 at 17 39 46" src="https://github.com/user-attachments/assets/378a5e9f-8f3a-4199-b137-311bb449d392">

- Kerning between `in` makes the space uneven
    <img width="386" alt="Screenshot 2024-10-08 at 17 27 14" src="https://github.com/user-attachments/assets/9ad69af6-ec37-4501-bc1d-8a3912bdb324">

Some of these might be related to some cases already reported in #130

**Comment by vv-monsalve** [comment]
@guidoferreyra, please take a look also at this one .

**Comment by vv-monsalve** [comment]
`tcaron` also needs to be fixed.


<img width="160" alt="Screenshot 2024-10-08 at 16 11 12" src="https://github.com/user-attachments/assets/c7297d18-67bb-4336-850e-4502e4f7f18c">

**Comment by guidoferreyra** [comment]
@vv-monsalve please check https://github.com/vercel/geist-font/tree/%23135-fixes

**Comment by vv-monsalve** [comment]
This has been solved in the `#135-fixes branch` at commit `d8c9d65`.
