### ISSUE TITLE
**FAIL** Overlaying path segments

### ISSUE THREAD

**Issue by vv-monsalve** [vercel/geist-font#139]
@guidoferreyra The following check was implemented after seeing some issues for outlines with coincident paths and it is reporting a Fails status for the Geist fonts

- [x] Geist Sans

<details>
    <summary>🔥 <b>FAIL</b> Check there are no overlapping path segments <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/outline.html#"></a></summary>
    <div>

> 
> Some rasterizers encounter difficulties when rendering glyphs with
> overlapping path segments.
> 
> A path segment is a section of a path defined by two on-curve points.
> When two segments share the same coordinates, they are considered
> overlapping.
> 

> Original proposal: https://github.com/google/fonts/issues/7594#issuecomment-2401909084

* 🔥 **FAIL** <p>The following glyphs have overlapping path segments:</p>
<pre><code>* uni0416 (U+0416): L&lt;&lt;616.0,355.0&gt;--&lt;500.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni0416 (U+0416): L&lt;&lt;428.0,355.0&gt;--&lt;311.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni041A (U+041A): L&lt;&lt;288.0,355.0&gt;--&lt;171.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni040C (U+040C): L&lt;&lt;288.0,355.0&gt;--&lt;171.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni0496 (U+0496): L&lt;&lt;616.0,355.0&gt;--&lt;500.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni0496 (U+0496): L&lt;&lt;428.0,355.0&gt;--&lt;311.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni049A (U+049A): L&lt;&lt;288.0,355.0&gt;--&lt;171.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni0436 (U+0436): L&lt;&lt;578.0,265.0&gt;--&lt;467.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni0436 (U+0436): L&lt;&lt;395.0,265.0&gt;--&lt;282.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni043A (U+043A): L&lt;&lt;272.0,265.0&gt;--&lt;159.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni045C (U+045C): L&lt;&lt;272.0,265.0&gt;--&lt;159.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni0497 (U+0497): L&lt;&lt;578.0,265.0&gt;--&lt;467.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni0497 (U+0497): L&lt;&lt;395.0,265.0&gt;--&lt;282.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni049B (U+049B): L&lt;&lt;272.0,265.0&gt;--&lt;159.0,265.0&gt;&gt; has the same coordinates as a previous segment.
</code></pre>
 [code: overlapping-path-segments]

</div>
</details>

- [x] Geist Mono

<details>
    <summary>🔥 <b>FAIL</b> Check there are no overlapping path segments <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/outline.html#"></a></summary>
    <div>

> 
> Some rasterizers encounter difficulties when rendering glyphs with
> overlapping path segments.
> 
> A path segment is a section of a path defined by two on-curve points.
> When two segments share the same coordinates, they are considered
> overlapping.
> 

> Original proposal: https://github.com/google/fonts/issues/7594#issuecomment-2401909084

* 🔥 **FAIL** <p>The following glyphs have overlapping path segments:</p>
<pre><code>* uni0416 (U+0416): L&lt;&lt;426.0,355.0&gt;--&lt;333.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni0416 (U+0416): L&lt;&lt;267.0,355.0&gt;--&lt;174.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni041A (U+041A): L&lt;&lt;248.0,355.0&gt;--&lt;137.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni040C (U+040C): L&lt;&lt;248.0,355.0&gt;--&lt;137.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni0496 (U+0496): L&lt;&lt;409.0,355.0&gt;--&lt;320.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni0496 (U+0496): L&lt;&lt;256.0,355.0&gt;--&lt;167.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni049A (U+049A): L&lt;&lt;238.0,355.0&gt;--&lt;127.0,355.0&gt;&gt; has the same coordinates as a previous segment.

* uni0436 (U+0436): L&lt;&lt;432.0,265.0&gt;--&lt;336.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni0436 (U+0436): L&lt;&lt;264.0,265.0&gt;--&lt;168.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni043A (U+043A): L&lt;&lt;283.0,265.0&gt;--&lt;170.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni045C (U+045C): L&lt;&lt;283.0,265.0&gt;--&lt;170.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni0497 (U+0497): L&lt;&lt;432.0,265.0&gt;--&lt;336.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni0497 (U+0497): L&lt;&lt;264.0,265.0&gt;--&lt;168.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* uni049B (U+049B): L&lt;&lt;282.0,265.0&gt;--&lt;169.0,265.0&gt;&gt; has the same coordinates as a previous segment.

* asciitilde_at.liga: L&lt;&lt;-150.0,221.0&gt;--&lt;-150.0,143.0&gt;&gt; has the same coordinates as a previous segment.
</code></pre>
 [code: overlapping-path-segments]

</div>
</details>

<img width="600" alt="Screenshot 2024-10-22 at 18 51 41" src="https://github.com/user-attachments/assets/a472d853-5b7a-4545-87e8-e50c22540d66">

**Comment by guidoferreyra** [comment]
Oh this is a new check right? It was not reporting before I will fix it now.
