### ISSUE TITLE
Difference between Geist Font installed via package and the one on google fonts

### ISSUE THREAD

**Issue by gherardi** [vercel/geist-font#149]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [ ] Geist Mono (not tried)

**Description of the Issue:**
There is a clear difference between geist font imported via npm package and geist font imported via google font.

**Steps to Reproduce:**
1. create a new project utilizing t3 stack
2. use google fonts and you will notice that they are different

**Expected Behavior:**
A difference between the two fonts, although they should be the same, only the way they are “imported” changes

**Screenshots:**
![geist-browser](https://github.com/user-attachments/assets/c6ab58ba-f01f-4f02-b3d7-97df0ca205e4)
![code](https://github.com/user-attachments/assets/eea0180c-96a0-4e8f-bbc9-3f3d75ec235a)

**Environment (please complete the following information):**
 - OS: Windows
 - Software: Chrome (latest version)

**Additional Context:**
I was following a tutorial using the t3 stack, it installs the geist font.
I tried to use the geist font using google font and came across this difference between these two versions of using it

**Comment by urbansheep** [comment]
Also Google Fonts version doesn't include cyrillic support, while the Geist from releases had cyrillics support since last year.

**Comment by dmythro** [comment]
Seems like there's a version mismatch in different places. NPM has latest version `1.3.1`, but here we see `1.4.01`.
Could you please fix this and align all versions?

**Comment by gherardi** [comment]
Fixed, I had to manually install the latest version of the font because pnpm add geist would not install the latest version
