### ISSUE TITLE
Add Geist Mono to Nerd Fonts

### ISSUE THREAD

**Issue by QuiiBz** [vercel/geist-font#18]
[Nerd Fonts](https://nerdfonts.com) is heavily used to generate patched programming fonts with many useful icons. After reading the license, I *think* it's something that's permitted and would benefit many folks.

I made a PR upstream to the Nerd Fonts repo to add & patch Geist Mono: https://github.com/ryanoasis/nerd-fonts/pull/1398

**Comment by QuiiBz** [comment]
I think we just have to wait for a new review on https://github.com/ryanoasis/nerd-fonts/pull/1398 - Finii also [mentioned](https://github.com/ryanoasis/nerd-fonts/pull/1398#issuecomment-1783798336) the `0` vs `O` differentiation issue, but that doesn't seem to be a blocker.

I opened this issue to have a link back from the upstream PR on Nerd Fonts' repo, there is no precise work needed here.

**Comment by daiyam** [comment]
The `0` and `O` differentiation issue is being discuss at https://github.com/vercel/geist-font/issues/23

**Comment by JohnPhamous** [comment]
Fixed and available in the `1.0.1` release on [GitHub](https://github.com/vercel/geist-font/releases/tag/1.0.1) and on [npm](https://www.npmjs.com/package/geist).

**Comment by QuiiBz** [comment]
Amazing, I've just updated the upstream [Nerd Fonts PR](https://github.com/ryanoasis/nerd-fonts/pull/1398) to use `1.0.1`.

**Comment by emapeire** [comment]
Let's rock guys! Thanks 🤩

**Comment by QuiiBz** [comment]
Closing as it has been released in Nerd Fonts 3.1.0: https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.1.0
