### ISSUE TITLE
Publish a CSS file with the fonts?

### ISSUE THREAD

**Issue by omar2205** [vercel/geist-font#21]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
It would be helpful to have a CSS file to load the fonts. I want to use it from a CDN like unpkg.com (like so https://unpkg.com/browse/geist@1.0.0/dist/font.css) where font.css loads the font files.

**Comment by michael-andreuzza** [comment]
+1

**Comment by JohnPhamous** [comment]
We do not recommend using the font in your website/application through a CDN. To learn more check out the `next/font` documentation: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts

**Comment by omar2205** [comment]
Most of the projects I work on aren't React/Nextjs.

**Comment by JohnPhamous** [comment]
We recommend self-hosting the font with your website. Which framework are you using?

**Comment by JohnPhamous** [comment]
We recommend self-hosting the font with your website. Which framework are you using?

**Comment by omar2205** [comment]
Vanilla or Svelte/Sveltekit. It's fine, I will self-host 😅.

Have a nice day :)
