### ISSUE TITLE
Languages: 32, But Which?

### ISSUE THREAD

**Issue by satoi8080** [vercel/geist-font#22]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [x] Geist Mono

**Description of the Issue:**

The homepage states that the font supports 32 languages, but there is no accompanying list to specify which languages are supported. Additionally, it's unclear if the font supports CJK (Chinese, Japanese, Korean) characters.

**Comment by jung-han** [comment]
Agree

**Comment by harrisrobin** [comment]
yes i have the same question, i am wondering if it works for Arabic

**Comment by mybearworld** [comment]
This font seems to only support Latin based languages. CJK and Arabic are *not* supported.

**Comment by guidoferreyra** [comment]
The fonts supports the following languages:

**Latin Script (294 languages):**  
Acheron, Achinese, Acholi, Achuar-Shiwiar, Afar, Afrikaans, Aguaruna, Ahtna, Alekano, Aleut, Amahuaca, Amarakaeri, Amis, Anaang, Andaandi, Dongolawi, Anuta, Aragonese, Arbëreshë Albanian, Asháninka, Ashéninka Perené, Atayal, Balinese, Bari, Basque, Batak Dairi, Batak Karo, Batak Mandailing, Batak Simalungun, Batak Toba, Bemba (Zambia), Bena (Tanzania), Bikol, Bislama, Borana-Arsi-Guji Oromo, Bosnian, Breton, Buginese, Candoshi-Shapra, Caquinte, Caribbean Hindustani, Cashibo-Cacataibo, Cashinahua, Catalan, Cebuano, Central Aymara, Central Kurdish, Chachi, Chamorro, Chavacano, Chiga, Chiltepec Chinantec, Chokwe, Chuukese, Cimbrian, Cofán, Cook Islands Māori, Cornish, Corsican, Creek, Crimean Tatar, Croatian, Czech, Danish, Dehu, Dimli, Dutch, Eastern Arrernte, Eastern Oromo, English, Faroese, Fijian, Filipino, Finnish, French, Friulian, Gagauz, Galician, Ganda, Garifuna, German, Gheg Albanian, Gilbertese, Gooniyandi, Gourmanchéma, Guadeloupean Creole French, Gusii, Haitian, Hani, Hiligaynon, Hopi, Huastec, Hungarian, Hän, Icelandic, Iloko, Inari Sami, Indonesian, Irish, Istro Romanian, Italian, Ixcatlán Mazatec, Jamaican Creole English, Japanese, Javanese, Jola-Fonyi, K'iche', Kabuverdianu, Kaingang, Kalaallisut, Kalenjin, Kamba (Kenya), Kaonde, Kaqchikel, Karelian, Kashubian, Kekchí, Kenzi, Mattokki, Khasi, Kikuyu, Kimbundu, Kinyarwanda, Kirmanjki, Kituba (DRC), Kongo, Konzo, Kven Finnish, Kölsch, Ladin, Ladino, Latgalian, Lithuanian, Lombard, Low German, Lower Sorbian, Lozi, Luba-Lulua, Lule Sami, Luo (Kenya and Tanzania), Luxembourgish, Macedo-Romanian, Makonde, Malagasy, Malaysian, Maltese, Mandinka, Mandjak, Mankanya, Manx, Maore Comorian, Maori, Mapudungun, Marshallese, Matsés, Mauritian Creole, Meriam Mir, Meru, Minangkabau, Mirandese, Mohawk, Montenegrin, Munsee, Murrinh-Patha, Muslim Tat, Mwani, Mískito, Naga Pidgin, Ndonga, Neapolitan, Ngazidja Comorian, Niuean, Nobiin, Nomatsiguenga, North Azerbaijani, North Ndebele, Northern Kurdish, Northern Qiandong Miao, Northern Sami, Northern Uzbek, Norwegian, Nyanja, Nyankole, Occitan, Ojitlán Chinantec, Orma, Oroqen, Otuho, Palauan, Pampanga, Papantla Totonac, Papiamento, Paraguayan Guaraní, Pedi, Picard, Pichis Ashéninka, Piemontese, Pijin, Pintupi-Luritja, Pipil, Pite Sami, Pohnpeian, Polish, Portuguese, Potawatomi, Purepecha, Páez, Quechua, Romanian, Romansh, Rotokas, Rundi, Samoan, Sango, Sangu (Tanzania), Saramaccan, Sardinian, Scots, Scottish Gaelic, Sena, Serbian, Seri, Seselwa Creole French, Shawnee, Shipibo-Conibo, Shona, Shuar, Sicilian, Silesian, Skolt Sami, Slovak, Slovenian, Soga, Somali, Soninke, South Azerbaijani, South Ndebele, Southern Aymara, Southern Qiandong Miao, Southern Sami, Southern Sotho, Spanish, Sranan Tongo, Standard Estonian, Standard Latvian, Standard Malay, Sundanese, Swahili, Swedish, Swiss German, Tagalog, Tahitian, Talysh, Tedim Chin, Tetum, Tetun Dili, Toba, Tojolabal, Tok Pisin, Tokelau, Tonga (Tonga Islands), Tonga (Zambia), Tosk Albanian, Tsakhur, Tumbuka, Turkish, Turkmen, Tzeltal, Tzotzil, Uab Meto, Umbundu, Ume Sami, Upper Guinea Crioulo, Upper Sorbian, Venetian, Veps, Võro, Walloon, Walser, Waray (Philippines), Warlpiri, Wayuu, Welsh, West Central Oromo, Western Abnaki, Western Frisian, Wiradjuri, Wolof, Xhosa, Yanesha', Yao, Yucateco, Zapotec, Zulu, Zuni, Záparo.  

**Cyrillic Script: (47 languages)**
Abaza, Adyghe, Aghul, Archi, Avaric, Belarusian, Bezhta, Budukh, Chamalal, Chechen, Chinese Buriat, Crimean Tatar, Dargwa, Dido, Dungan, Erzya, Halh Mongolian, Ingush, Judeo-Tat, Kabardian, Kalmyk, Karachay-Balkar, Karata, Kazakh, Khinalugh, Kirghiz, Kumyk, Lak, Lezghian, Macedonian, Moksha, Mongolian Buriat, Montenegrin, Muslim Tat, Nogai, Russian, Russian Buriat, Rusyn, Rutul, Serbian, Shughni, Tabassaran, Tajik, Tatar, Tsakhur, Tuvinian, Ukrainian.
