### ISSUE TITLE
Add Geist to Google Fonts

### ISSUE THREAD

**Issue by eliheuer** [vercel/geist-font#25]
This is a great project and I would love to see it available on [Google Fonts ](https://fonts.google.com/).

Me or anyone else with experience onboarding fonts to Google Fonts would be happy to help move this through the onboarding pipeline, there is already an issue https://github.com/google/fonts/issues/6922 in the Google Fonts Git repository asking for it to be included in the collection.

A guide covering all the technical requirements for inclusion in the Google Fonts catalog is [available here](https://googlefonts.github.io/gf-guide/), but the technical details can be handled by the people onboarding the fonts.

**Comment by weleo** [comment]
This would also make it accessible in package managers like Homebrew as a side effect. Projects such as homebrew-cask-fonts include all the fonts available on Google Fonts.

**Comment by emapeire** [comment]
Actually this will help us to improve the initialization with next/font.

**Comment by bdsqqq** [comment]
+1 Would love using Geist in weird places that take any Google fonts (very relevant to oddly specific use-cases I have, eg: making Geist the default font in a modified spotify client without needing the consumer to download the font manually).

**Comment by cowboycodr** [comment]
Just commenting so this issue gets more attention.

Absolutely crazy that an open-source project is moving as slow as a bureaucracy. Why can't we just get it in to Google Fonts already? People are literally willing to do it for you.

**Comment by guidoferreyra** [comment]
The font is still on the works and there would be some changes that are much better to do before onboarding to GF. Once the font is available publicly there, is much more complex to do breaking changes since affects a lot of website and users.

**Comment by guidoferreyra** [comment]
Closing in favor of #99
