### ISSUE TITLE
Adding License.txt to Subsequent Releases

### ISSUE THREAD

**Issue by JinPlanter** [vercel/geist-font#26]
Hi, to preface this isn't a bug per se with the font project:

I'd like to suggest adding the LICENSE.txt file to all subsequent releases of Geist-font as it helps your users abide by your licensing terms and prevents any accidental or intentional license violations.

I checked and saw that both Source archives [zip and tar] contains the license agreement.
So it's just Geist.zip and Geist.Mono.zip that you might want to consider adding in the license before releasing

Thanks!

**Comment by JohnPhamous** [comment]
Thanks! We will make sure all subsequent releases includes the license in the zips.
