### ISSUE TITLE
No Cyrillic support

### ISSUE THREAD

**Issue by dimitur2204** [vercel/geist-font#36]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
I think it is quite self-descriptive. There is no _Cyrillic_ support.

**Screenshots:**
<img width="328" alt="image" src="https://github.com/vercel/geist-font/assets/61479393/94ac9477-8e26-4c96-9087-bfa516d6eddd">

**Environment (please complete the following information):**
 - OS: MacOS Sonoma 14.1 (23B73)
 - Software: Google Chrome
 - Version of the Font: 1.0

**Additional Context:**
Great work on the font! 🤩
However _Cyrillic_ is a gamechanger for many people around the world :)
I personally try to never use different fonts for _Cyrillic_ and _Latin_ versions of my websites and a font supporting both is the first thing I look at.

**Comment by yarikpetrenko** [comment]
+1

**Comment by piscopancer** [comment]
+1

**Comment by BorisChumichev** [comment]
+1

**Comment by vestimir** [comment]
+1 and with proper support for Bulgarian and Russian letters, like Apple's San Francisco – https://cyrillic.bgweb.bg/en/

**Comment by HighError** [comment]
+1 for Ukrainian

**Comment by renatlb** [comment]
+1 for extended Cyrillic set

**Comment by aq1** [comment]
Looks like they added it. Or is it some kind of fallback font?

<img width="1193" alt="image" src="https://github.com/vercel/geist-font/assets/3045638/4b1752bf-72b1-4ea3-b48b-0ba61eb7b319">

**Comment by yarikpetrenko** [comment]
Yeah, v1.1.0 adds support for Cyrillic characters https://github.com/vercel/geist-font/releases/tag/1.1.0

**Comment by guidoferreyra** [comment]
The typeface supports cyrillic but there design fixes to do eg: #84

**Comment by vestimir** [comment]
@guidoferreyra does it also include extended cyrillic support for character alternatives?

**Comment by vestimir** [comment]
@guidoferreyra great! Testing it right now :)
