### ISSUE TITLE
Capital ẞ doesn't look much like a usual capital ẞ

### ISSUE THREAD

**Issue by mybearworld** [vercel/geist-font#39]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
Usually, the capital ẞ is differentiated from ß via two things. Geist doesn't do either correctly:
1. **A wider character.** Geist doesn't have much of a difference between ẞ and ß here.
2. **A less curly body.** While Geist does do that, it makes the bizarre decision to also flatten the top. This is very unusual and while readable, really does not look much like ẞ.

**Steps to Reproduce:**
1. Type a string with the capital ẞ like `ICH WOHNE IN GIEẞEN`.

**Expected Behavior:**
Geist has a more conventional ẞ.

**Screenshots:**
Geist Sans:
![Screenshot of the capital ẞ and its lowercase variant ß from the Geist web page. The capital ẞ has a slightly less curly body, which is usual. However, it is not wider than its lowercase variant, and the top is flat.](https://github.com/vercel/geist-font/assets/130385691/9fb5d1d1-59fe-4b90-870d-84fba67f288a)

Open Sans:
![Screenshot of the capital ẞ and its lowercase variant ß as used in the Open Sans font. The capital looks like the conventional ẞ, with a curly top, but a bit longer than ß and less curly in the body.](https://github.com/vercel/geist-font/assets/130385691/e9601c4f-40a5-47a2-a839-a199f07ebbf4)

**Environment (please complete the following information):**
 - OS: N/A
 - Software: N/A
 - Version of the Font: 1.0

**Additional Context:**
None

**Comment by BKR-dev** [comment]
I want to emphasise that is a non trivial issue to use the font for German, a clear distinction between upper and lower case ß is important. Thanks @mybearworld for spotting this!

**Comment by JohnPhamous** [comment]
Fixed in #44.
