### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [vercel/geist-font#41]
Hi,
Would you mind changing the OFL license to the version without "reserved font name" so it can be added to Google Fonts? Thanks!
NB: I'm not affiliated with Google

**Comment by JohnPhamous** [comment]
We are already in the process of getting the font into Google Fonts.

**Comment by fakerybakery** [comment]
Hi, I'm pretty sure unfortunately Google Fonts only allows fonts without the reserved font name version of OFL

**Comment by davelab6** [comment]
@fakerybakery fortunately Google Fonts can accept fonts with an RFN, if Google is given the additional permission required by the license. This is explained in https://googlefonts.github.io/gf-guide/license-file.html with a template email to give such permission :)
