### ISSUE TITLE
Request italic font files

### ISSUE THREAD

**Issue by jessypouliot98** [vercel/geist-font#42]
**Font Name (Geist Sans/Geist Mono):**
- [X] Geist Sans
- [X] Geist Mono

**Description of the Issue:**
I want to use the `Geist Sans` font in `react-pdf`. My use case requires _italics_ to enable them I need to register the font file which it doesn't exist. My current fallback is to define the italic variant as a non-italic variant, otherwise the pdf generation fails.

**Screenshots:**
```typescript
    Pdf.Font.register({
      family: "Geist",
      fonts: [
        { src: path.resolve(fontPath, "Geist-Regular.woff2"), fontWeight: "normal" },
        { src: path.resolve(fontPath, "Geist-Regular.woff2"), fontWeight: "normal", fontStyle: "italic" }, // Not actually italic
        { src: path.resolve(fontPath, "Geist-Bold.woff2"), fontWeight: "bold" },
        { src: path.resolve(fontPath, "Geist-Bold.woff2"), fontWeight: "bold", fontStyle: "italic" },  // Not actually italic
      ]
    });
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Software: react-pdf
 - Version of the Font: 1.0

**Comment by JohnPhamous** [comment]
Thank you for the request. Going to merge this with #29.

**Comment by ihfandicahyo** [comment]
Wait, hello.
Does now is support _italic_ for Geist-Sans?
I use for android and missing _italic_ style or i have a skill problem?

**Comment by augiethehuman** [comment]
> Wait, hello. Does now is support _italic_ for Geist-Sans? I use for android and missing _italic_ style or i have a skill problem?

Hey won't make it.
