### ISSUE TITLE
[Question] Using icons

### ISSUE THREAD

**Issue by rafbgarcia** [vercel/geist-font#43]
Hi folks, thanks for the new font, I love it!

I have one quick question: how can I use the icons you mentioned?

Thanks!

<img width="466" alt="Geist_Font_—_Vercel" src="https://github.com/vercel/geist-font/assets/1904314/1f733e65-276e-47fe-a884-c2822fa59a9b">

**Comment by mwskwong** [comment]
For now, Vercel is using a modified version of Feather icons, which is fairly similar to what is being displayed there. You may also take a look at [Lucide icons](https://lucide.dev/), which is a fork of Feather icons for a larger icon set.

**Comment by rafbgarcia** [comment]
@mwskwong sounds good, thank you for your reply!
