### ISSUE TITLE
v1.002 Yen ¥ bars are offset in Thin

### ISSUE THREAD

**Issue by kenmcd** [vercel/geist-font#49]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [ ] Geist Mono

Version: Geist.v1.002.(2023-11-07) from v1.0.1 release
Files: `GeistVariableVF.ttf` and `Geist-Thin.otf`

The horizontal bars on the Yen symbol (`00A5`) are offset to the right in the Thin master.

The image below is from the Thin static font.
Looks the same in the VF Thin instance.

![Yen-bars-offset](https://github.com/vercel/geist-font/assets/844920/e65f4807-6ee7-402d-a082-628bc6797e3c)

**Comment by guidoferreyra** [comment]
This was fixed on [1.100](https://github.com/vercel/geist-font/releases/tag/1.1.0) version
