### ISSUE TITLE
'fi' ligature has very large spacing

### ISSUE THREAD

**Issue by glennui** [vercel/geist-font#55]
**Font Name (Geist Sans/Geist Mono):**
- [ ] Geist Sans

**Description of the Issue:**

https://github.com/vercel/geist-font/assets/4420570/fdfe9625-cfb0-4eff-8fec-e310fd12d19e

**Steps to Reproduce:**
1. Try entering a word with 'fi' in Figma
2. Enable/disable ligatures

**Expected Behavior:**
I would think if there's no actual join between `fi` then the spacing should remain consistent across ligatures/no ligatures. 

Alternatively, is there supposed to be a join between them?

**Comment by guidoferreyra** [comment]
This is not longer visible on the latest release https://github.com/vercel/geist-font/releases/tag/1.3.0
