### ISSUE TITLE
Geist-font works only in Next.js

### ISSUE THREAD

**Issue by contigen** [vercel/geist-font#62]
Hi! It's a good font, thank you, and it's a bummer we can't get to use the package on non-Next.js libraries/frameworks.
Is there a way `geist-font` can be used in React & others, or it's not just supported?
Thanks.

**Comment by enchorb** [comment]
+1 wanted to use this in React Native

**Comment by contigen** [comment]
Hey! You can actually download from vercel.com/font

**Comment by Dax911** [comment]
> So I did this, a package that allows you to Geist Sans & Mono outside of Next.js
> 
> https://www.npmjs.com/package/non.geist

Hero

**Comment by zwhitchcox** [comment]
> > So I did this, a package that allows you to Geist Sans & Mono outside of Next.js
> > https://www.npmjs.com/package/non.geist
> 
> Hero

Not all heroes wear capes

**Comment by briannarenni** [comment]
> So I did this, a package that allows you to Geist Sans & Mono outside of Next.js
> 
> https://www.npmjs.com/package/non.geist

Still a hero, I found this by the same "how to use Geist outside of Next" search haha.
