### ISSUE TITLE
[Mono] Incompetibale `─` and `-` with fallbacked box-darwing characters

### ISSUE THREAD

**Issue by mwskwong** [vercel/geist-font#64]
**Font Name (Geist Sans/Geist Mono):**
- [ ] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
Example usage: `├──`, commonly found in the output of `tree` command.

In this case, Geist Mono doesn't have a `├` character, so it falls back to OS monospace font. Yet, the recent update seems to have changed the style of `-` and `─`, causing it to misalign with the fallback `├` character

**Steps to Reproduce:**
1. Make use of the Geist Mono font and type `├──`

**Expected Behavior:**
`├──` should be aligned

**Screenshots:**
![image](https://github.com/vercel/geist-font/assets/32725014/69fb7b4e-cf72-4434-9e81-a0b85a67f068)

**Environment (please complete the following information):**
 - OS: MacOS
 - Software: Edge
 - Version of the Font: 1.1.0

**Additional Context:**
This issue is not observed in `1.0.1`

**Comment by mwskwong** [comment]
![Screenshot_2024-01-13-10-40-20-631_com android chrome-edit](https://github.com/vercel/geist-font/assets/32725014/04ae2799-d6c6-4f74-9c37-8e291e01b62e)

It still doesn't work too well in Chrome Android. IMO, either provide all commonly used box characters. Or not include any of them in the font. Or else it will always run into compatibility issues with the fallback font.

**Comment by souporserious** [comment]
Can confirm this is fixed in 1.3.0, thank you!
 
<img width="227" alt="image" src="https://github.com/vercel/geist-font/assets/2762082/f7c71849-2289-44df-82ad-b0e634261c63">
