### ISSUE TITLE
Request for ligature character for `???`

### ISSUE THREAD

**Issue by chengluyu** [vercel/geist-font#67]
**Font Name (Geist Sans/Geist Mono):**
- [ ] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
Please provide a clear and concise description of the issue.

**Steps to Reproduce:**

N/A

**Expected Behavior:**

[`???`](http://dotty.epfl.ch/api/scala/Predef$.html#???-0) can be used for marking methods that remain to be implemented in Scala. Geist Mono includes ligature character for `??` only and applies it to the first two `?` of `???`, which looks very inconsistent.

**Screenshots:**

<img width="132" alt="image" src="https://github.com/vercel/geist-font/assets/2239547/44ca6707-5abe-4033-99a0-2cd8a8884f64">

**Environment (please complete the following information):**
 - OS: macOS
 - Software: Visual Studio Code
 - Version of the Font: 1.1.0

**Additional Context:**

N/A

**Comment by JohnPhamous** [comment]
Thanks for the feature request. We've added the new character in #78. It's available in version `0.2.1`.
