### ISSUE TITLE
Add powerline characters

### ISSUE THREAD

**Issue by T04435** [vercel/geist-font#69]
**Font Name (Geist Sans/Geist Mono):**
- [ ] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
Please provide a clear and concise description of the issue.

**Steps to Reproduce:**
1. Set font in a powerline terminal
2. warp > settings > appearance > select GeistMono font

**Expected Behavior:**
Special characters to show

**Screenshots:**
JetBrainsMono Powerline terminal(👍🏼)
![Screenshot 2023-12-06 at 9 57 56 am](https://github.com/vercel/geist-font/assets/10654469/484b037c-3ca9-4112-a9de-68a76fc13ac0)

GeistMono Powerline terminal(👎🏼)
![Screenshot 2023-12-06 at 9 58 14 am](https://github.com/vercel/geist-font/assets/10654469/f713f722-0107-4574-8cd3-2a8e6a233f2e)

**Environment (please complete the following information):**
 - OS: MacOS
 - Software: Warp + ohmyzsh + agnoster theme
 - Version of the Font: 1.1.0

**Additional Context:**
A list of known powerline fonts => https://github.com/powerline/fonts

**Comment by Tylopilus** [comment]
A version has been added to nerd-fonts:
https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.1.0

**Comment by T04435** [comment]
@Tylopilus This is still an issue the font still does not have the powerline characters
