### ISSUE TITLE
[Question] Language coverage

### ISSUE THREAD

**Issue by brandaohh** [vercel/geist-font#70]
It is stated that Vercel covers 32 languages, is it possible to get a list of these languages? Also, do you plan on covering more languages in the future?

**Comment by inferno986return** [comment]
Looks like just Latin alphabet languages judging by the glyphset shown on the website. Latin is the most used writing system in the world. Language support tends to be listed exhaustively, so here are some examples: 

* Albanian
* Basque
* Catalonian
* Cornish
* Corsican
* Czech
* English
* Esperanto (presence of the letters ĉ, ĝ, ĥ, ĵ, ŝ and ŭ)
* Extramedurian
* French
* Guarani
* Hungarian
* Irish
* Manx
* Maori
* Polish
* Portuguese
* Romanian (presence of the letter ă)
* Slovakian
* Spanish
* etc.

I am using Geist as my default browser font and there's pretty good Latin coverage: https://en.wikipedia.org/wiki/Latin_Extended-A
https://en.wikipedia.org/wiki/Latin_Extended-B

It would be cool if there was a program which took a font file and could show its Unicode coverage and an exhaustive list of languages supported. 😊

**Comment by MarcusSterz** [comment]
https://hyperglot.rosettatype.com/ is a great resource.
