### ISSUE TITLE
Spacing issues

### ISSUE THREAD

**Issue by LosDragonflyos** [vercel/geist-font#73]
**Font Name (Geist Sans/Geist Mono):**
- [X] Geist Sans
- [ ] Geist Mono

**Description of the Issue:**
Too much space between certain characters; extra looks like ex tr a, for example. Baking is bak ing while korn works fine.

**Steps to Reproduce:**
Type out words like ‘extraño,’ ‘Wikinger,’ ‘buzzing.’ (xt/xx/ki/kk/kp/zz et c.)

**Expected Behavior:**
Visually pleasing spacing.

**Environment (please complete the following information):**
 - Software: Font Gauntlet
 - Version of the Font: 1.002

**Additional Context:**
I suggest using Hoefler’s proof to identify more issues—I am just a dude who likes typefaces.

**Comment by JohnPhamous** [comment]
Thanks for the bug report. We've cleaned up the spacings in #78. It's available in version `0.2.1`.
