### ISSUE TITLE
Some stylistic sets do not work for cyrillic equivalents of latin characters 

### ISSUE THREAD

**Issue by Emplexx** [vercel/geist-font#75]
**Font Name (Geist Sans/Geist Mono):**
- [X] Geist Sans
- [X] Geist Mono

**Description of the Issue:**
No tail a, Alt a, and Rounded dot stylistic sets do not work for the cyrillic characters `а` and `і`
![image](https://github.com/vercel/geist-font/assets/64900852/9e941f0c-9036-412f-8a7d-2dad1b3cbdef)

**Steps to Reproduce:**
1. Type anything in cyrillic that contains these letters, for example, 'Ціна'
2. Turn on either of the no tail a/alt a/rounded dot sets 
3. It doesn't work

**Expected Behavior:**
I expect stylistic sets to work with cyrillic 
![image](https://github.com/vercel/geist-font/assets/64900852/a09a7564-0e4f-49dc-8193-fb92bd5f943d)

**Environment (please complete the following information):**
 - OS: [Windows]
 - Software: [Figma]
 - Version of the Font: [e.g. 1.1.0]

**Comment by guidoferreyra** [comment]
it’s fixed on version 1.4.0.
