### ISSUE TITLE
Geist font not working with TailwindCSS

### ISSUE THREAD

**Issue by psiaux** [vercel/geist-font#82]
**Font Name (Geist Sans/Geist Mono):**
- [x] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
Geist font is not being applied to the elements. The inspection inside browser's debug tools shows `font-family: ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";`.

**Steps to Reproduce:**
1. Install Next.js and TailwindCSS with create-next-app
2. Import font `import { GeistSans } from 'geist/font/sans'`
3. Apply font `<html className={``${GeistSans.variable} ${GeistMono.variable} font-sans}``>`
4. Add Geist to TailwindCSS:
      `module.exports = { 
         theme: {
           extend: {
             fontFamily: {
               sans: ['var(--font-geist-sans)']
             }
           }
         }
       }`

**Expected Behavior:**
It should appear something like `font-family: var(--font-geist-sans); `on the inspection.

**Environment (please complete the following information):**
 - OS: Windows
 - Software: Opera GX
 - Version of the Font: ^1.2.1

**Comment by JohnPhamous** [comment]
Can you provide a repo or a codepen? It's very helpful to have the exact versions of everything when debugging these issues.

**Comment by psiaux** [comment]
I was making a repo for you, but I think I got it working. There were 2 taildwind config files, one .ts and one .js. I don't know why this .js was created. I deleted it and it started working.
