### ISSUE TITLE
400 and 300 font-weight issues with Variable file for Geist Sans

### ISSUE THREAD

**Issue by nitinmgarg** [vercel/geist-font#90]
**Font Name**
Geist Sans, Variable File Only

**Description of the Issue:**
In variable package, font-weight renders incorrectly for weight 400 and 300. 
It appears that 300 renders what is meant to be regular, and 400 renders a light or ulralight version. 

**Steps to Reproduce:**
1. Only Install variable font-file for Geist Sans
2. Open in Fontbook and review weight rendering for Light and Regular
3. Or use as webfont and apply font-weight 400, which leads to a rendering light or ultralight

**Expected Behavior:**
font-weight 400 leading to rendering regular weight

**Screenshots:**
![fw-light](https://github.com/vercel/geist-font/assets/1174597/8a485f84-209d-49d9-9c02-71d0382062a5)
![fw-regular](https://github.com/vercel/geist-font/assets/1174597/9679f556-19c3-4b0b-826b-14f69696bdf5)

**Environment (please complete the following information):**
 - OS: MacOS Sonoma 14.2
 - Fontbook, Chrome, Safari as Webfont
 - Version 1.2.2

**Additional Context:**

**Comment by huskyjp** [comment]
happened to me as well when using geist-sans font from zip download - npm package works correctly. Did you figure this out?

**Comment by guidoferreyra** [comment]
This should be fixed on the latest release https://github.com/vercel/geist-font/releases/tag/1.3.0

**Comment by huskyjp** [comment]
nice thanks
