### ISSUE TITLE
Need help installing font in react app and tailwind css

### ISSUE THREAD

**Issue by dennis777** [vercel/geist-font#94]
Hello, this is not really an issue and more of a support thing

I'm fairly new to web development I was just wondering how to get this font up and running in my vite react project with tailwind css. I tried to follow the [guide](https://www.npmjs.com/package/geist?activeTab=readme) but I can't get it to work, it just makes my entire webpage blank when rendering. 

When I try to apply the font like `<h2 className={GeistSans.className}>Hello</h2>` I get an error in my console 
```
TypeError: (0, import_local.default) is not a function. 
```

I downloaded the `.ttf` file and managed to get some form of the font to show up by putting this in my index.css file
```
@font-face {
  font-family: "Geist";
  src: url(./fonts/GeistVariableVF.ttf) format('truetype');
}
```

and then the following config in my tailwind.config.json
```
//...
theme: {
    extend: {
        fontFamily: {
            "giest": ["Geist", "Regular"],
        },
    }
}
//...
```

Doing so I was able to apply the font by doing  `<h2 className="font-geist">Hello</h2>` However the issue with this is I have no idea how to get all the different subtypes (ultralight, light, regular, medium, semibold, etc...) I think im just misunderstanding how this works but please feel free to educate me I'm here to learn. Thank you

**Comment by manylovv** [comment]
Hey @dennis777! I encountered the same problem and found a solution.

You should consider using an "Unfonts" plugin for vite: 

```ts
// vite.config.ts
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';
import Unfonts from 'unplugin-fonts/vite';

export default defineConfig({
  plugins: [
    react(),
    Unfonts({
      custom: {
        families: [
          {
            name: 'Geist',
            src: './src/assets/fonts/geist/*.ttf',
          },
        ],
      },
    }),
  ],
});
```

Now the font is loaded and we need to add it to the tailwind config:
```ts
// tailwind.config.js
export default {
   // ...
   theme: {
    extend: {
      fontFamily: {
        geist: ['Geist', 'sans-serif'],
      },
    },
  },
};
``` 

I hope it will help :)

**Comment by joshuaedo** [comment]
Additionally, remember to import the generated @font-face rules into your main.tsx file by adding the following line:

`import 'unfonts.css';`

Might save someone some time.

**Comment by georgi-chichev-hk** [comment]
Hey @manylovv, according to the docs there is no need to download the fonts if you install the package using npm. I followed the docs for my vite + tailwind project and I am getting the same error.

```
TypeError: (0 , import_local.default) is not a function
    at geist_font_sans.js?t=1721407227828&v=70508119:10:42
```

I've installed Geist using npm install geist.
I added the css variable to the tailwind.config.js theme.extend.

```
fontFamily: {
   sans: ['var(--font-geist-sans)'],
   mono: ['var(--font-geist-mono)'],
}
```

And I used the font following the documentation.

```ts
import { Outlet } from 'react-router-dom';
import { GeistSans } from 'geist/font/sans';

export default function AuthLayout() {
  return (
    <>
      <main className={`${GeistSans.variable}`}>
        <Outlet />
      </main>
    </>
  );
}
```

**Comment by robotkala** [comment]
Hi. followed @manylovv and it seems to be working, however to use the font globally i had to add this into my index.css:
```
html {
  font-family: Geist, serif;
}
```
Doesn't seem very tailwindy, any suggestions?

**Comment by refeals** [comment]
> Doesn't seem very tailwindy, any suggestions?

I did it like this:

```
  body {
    @apply font-geist;
  }
```
