### ISSUE TITLE
windows terminal warns geist mono is not monospaced

### ISSUE THREAD

**Issue by maheshrijal** [vercel/geist-font#96]
**Font Name (Geist Sans/Geist Mono):**
- [ ] Geist Sans
- [x] Geist Mono

**Description of the Issue:**
Please provide a clear and concise description of the issue.

**Steps to Reproduce:**
1. Install Geist Mono on Windows
2. Open Windows terminal navigate to settings > Defaults > Appearance
3. Under Font Face, enable the `Show all fonts` toggle
4. Select Geist Mono

**Expected Behavior:**
No warnings should show when selecting Geist Mono as the Font Face

**Screenshots:**
![image](https://github.com/vercel/geist-font/assets/62394512/0c735fcb-44fb-4001-b774-17e36cb11176)

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Software: [Windows Terminal]
 - Version of the Font: [1.3.0]

**Comment by guidoferreyra** [comment]
On version 1.4.0 the font includes some changes that allows systems to recognize it as a fully monospaced font. This should be fixed now. Please feel free to reopen the issue if you think is not.
