### ISSUE TITLE
Onboarding Geist to Google Fonts

### ISSUE THREAD

**Issue by yanone** [vercel/geist-font#99]
Hello.

I've been commissioned to onboard Geist to Google Fonts.

Here are a few things I found that we would require to change:
* License file as OFL.txt
* A bunch of metadata changes regarding the copyright
* UltraLight instance renamed to ExtraLight
* Vertical metrics changed so that line gap becomes 0, gap instead added to ascender and descender values
* Fonts to be built with `gftools builder`
* Font binaries to be present in the repository file structure.

Normally, I would make those changes and send you a PR back. But at least one of them (UltraLight instance name) may break existing text, so I wanted to communicate about that first. I mean, fonts hosted on GoogleFonts are in a separate environment to existing Geist fonts, but it may be inconvenient to keep two versions of sources around. I may also be able to come up with a build script that can rename the instance and not change the source.

Looking forward to your reply.

**Comment by guidoferreyra** [comment]
Hi @yanone! I’m helping the designers team to solve some issues and improve the tech quality of the font. After #25 we have been discusing internally about onboarding to GF and I mentioned the required breaking changes. It‘s very likely that those changes will be done to avoid having to different versions of Geist but in the next month or so.

I will keep you posted.

**Comment by yanone** [comment]
Excellent, thank you.

**Comment by davelab6** [comment]
We also need to resolve the rfn which can be done by someone from vercel emailing fonts@google.com with an rfn permission, there's an example email in the gf guide :) https://googlefonts.github.io/gf-guide/license-file.html

**Comment by Kitenite** [comment]
This would be very helpful, thank you!

**Comment by guidoferreyra** [comment]
hi @yanone we are resuming on the work this month to keep doing fixes and start to prepare the fonts for onboarding. There are some breaking issues taht needs to be done before the family goes to GF.
Following @davelab6 comment I will connect Vercel people with you this week.

**Comment by yanone** [comment]
Thank you for the update. I'll be out for July and August, so not much time left. If the fonts are ready during that time, better connect with Dave about handing the work to another onboarder. But summers are generally slow as other people also take time off.

**Comment by chrissimpkins** [comment]
Re-assigning from Yanone to @vv-monsalve.  Let's see if we can land this in Fonts in Q3

**Comment by guidoferreyra** [comment]
A temporary repo for the non mono family it’s available [here](https://github.com/guidoferreyra/Geist). I’m having an issue with customize.py see [here](https://github.com/googlefonts/googlefonts-project-template/issues/177)

**Comment by romannurik** [comment]
👀 
https://fonts.google.com/specimen/Geist
https://fonts.google.com/specimen/Geist+Mono
